name: CD

on:
  push:
    branches: [ master ]

jobs:
  e2e:
      runs-on: ubuntu-latest
      steps:
        - name: Get application
          uses: actions/checkout@v2
          with:
            path: main

        - name: get Cypress
          uses: actions/checkout@v2
          with: 
            repository: 'nikolasFreitas/cypress-e-coffre-frontend'
            path: cypress

        - name: run application
          uses: actions/setup-node@v2
          with:
            node-version: 14

        - name: Installing app
          working-directory: main
          run: yarn
        - name: Running app
          working-directory: main
          run: yarn start&

        - name: Cypress run
          uses: cypress-io/github-action@v2
          with:
            working-directory: cypress
            browser: chrome
            headless: true
            record: false
  build:
    needs: e2e
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set Actions Allow Unsecure Commands
      run: |
        echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

    - name: Run install, build and test before deploy
      run: |
        set PUBLIC_URL=https://githiago-f.github.io/e-coffee-frontend/
        yarn
        yarn test
        yarn build

    - name: Run deploy
      uses: JamesIves/github-pages-deploy-action@3.5.7
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
