# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install application
        run: yarn
      - name: test application
        run: yarn test
      - name: eslint check
        run: yarn lint
      - name: build application
        run: yarn build

  e2e:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Get application
        uses: actions/checkout@v2
        with:
          path: main

      - name: get Cypress
        uses: actions/checkout@v2
        with: 
          repository: 'nikolasFreitas/cypress-e-coffre-frontend'
          path: cypress

      - name: run application
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Installing app
        working-directory: main
        run: yarn
      - name: Running app
        working-directory: main
        run: yarn start&

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: cypress
          browser: chrome
          headless: true
          record: false
