name: cypress test

on: 
  [push]
  # push: 
    # branches: [gh-pages]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Get application
        uses: actions/checkout@v2
          with:
            path: main

      - name: get Cypress
        uses: actions/checkout@v2
        with: 
          repository: 'nikolasFreitas/cypress-e-coffre-frontend'
          path: cypress

      - shell: bash
        run: |
          ls

      - name: run application
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: start application
        working-directory: cypress
        run: yarn
        run: yarn start

      - name: Cypress run
        uses: cypress-io/github-action@v2
        working-directory: cypress
        with:
          browser: chrome
          headless: true
          record: false
