name: cypress test

on: 
  [push]
  # push: 
    # branches: [gh-pages]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: get Cypress
        uses: actions/checkout@v2
        with: 
          repository: 'nikolasFreitas/cypress-e-coffre-frontend'
      - name: export gh-pages
        run: export CYPRESS_BASE_URL=${{ secrets.git_hub_pages }}
      - run: "echo \"Cypress url: $CYPRESS_BASE_URL\""
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
        env: 
          CYPRESS_BASE_URL: ${{ secrets.PAGES_URL }}
